@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu May 28 00:17:01 +0800 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim cpu_one_circle_tb_TA_time_synth -key {Post-Synthesis:sim_1:Timing:cpu_one_circle_tb_TA} -tclbatch cpu_one_circle_tb_TA.tcl -view D:/VivadoProject/COD/Lab3/Single_Cycle_CPU/dbu_tb_TA_behav.wcfg -log simulate.log"
call xsim  cpu_one_circle_tb_TA_time_synth -key {Post-Synthesis:sim_1:Timing:cpu_one_circle_tb_TA} -tclbatch cpu_one_circle_tb_TA.tcl -view D:/VivadoProject/COD/Lab3/Single_Cycle_CPU/dbu_tb_TA_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
