# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VivadoProject/Nexys-4-DDR-Master.xdc

# IP: ip/instr_mem_256x32/instr_mem_256x32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==instr_mem_256x32 || ORIG_REF_NAME==instr_mem_256x32} -quiet] -quiet
