# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VivadoProject/Nexys-4-DDR-Master.xdc

# IP: ip/dist_mem_512x32/dist_mem_512x32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_512x32 || ORIG_REF_NAME==dist_mem_512x32} -quiet] -quiet
