# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VivadoProject/COD/Lab4/Multicycle_CPU_new/Multicycle_CPU_new.srcs/sources_1/ip/dist_mem_512x32/dist_mem_512x32.xci
# IP: The module: 'dist_mem_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/COD/Lab4/Multicycle_CPU_new/Multicycle_CPU_new.srcs/sources_1/ip/dist_mem_512x32/dist_mem_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_512x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/VivadoProject/COD/Lab4/Multicycle_CPU_new/Multicycle_CPU_new.srcs/sources_1/ip/dist_mem_512x32/dist_mem_512x32.xci
# IP: The module: 'dist_mem_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/COD/Lab4/Multicycle_CPU_new/Multicycle_CPU_new.srcs/sources_1/ip/dist_mem_512x32/dist_mem_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_512x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
