# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cos.xdc

# IP: ip/ROM_Instruction/ROM_Instruction.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_Instruction || ORIG_REF_NAME==ROM_Instruction} -quiet] -quiet
