webtalk_init -webtalk_dir D:/VivadoProject/COD/Lab3/Single_Cycle_CPU/Single_Cycle_CPU.sim/sim_1/synth/func/xsim/xsim.dir/dbu_tb_TA_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 28 00:43:59 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211801393_0_0_301" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "92270b96-eab2-4e70-946e-d247f580aef0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cddfca8622214ec2a777651aea810133" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4702HQ CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17004_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2033717468 -regid "211801393_0_0_301" -xml D:/VivadoProject/COD/Lab3/Single_Cycle_CPU/Single_Cycle_CPU.sim/sim_1/synth/func/xsim/xsim.dir/dbu_tb_TA_func_synth/webtalk/usage_statistics_ext_xsim.xml -html D:/VivadoProject/COD/Lab3/Single_Cycle_CPU/Single_Cycle_CPU.sim/sim_1/synth/func/xsim/xsim.dir/dbu_tb_TA_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm D:/VivadoProject/COD/Lab3/Single_Cycle_CPU/Single_Cycle_CPU.sim/sim_1/synth/func/xsim/xsim.dir/dbu_tb_TA_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
