# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VivadoProject/COD/Lab5/cpu_pipeline_IDbeq_forward_predictor/cpu_pipeline_IDbeq_forward_predictor.srcs/sources_1/ip/data_mem_256x32/data_mem_256x32.xci
# IP: The module: 'data_mem_256x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/COD/Lab5/cpu_pipeline_IDbeq_forward_predictor/cpu_pipeline_IDbeq_forward_predictor.srcs/sources_1/ip/data_mem_256x32/data_mem_256x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mem_256x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/VivadoProject/COD/Lab5/cpu_pipeline_IDbeq_forward_predictor/cpu_pipeline_IDbeq_forward_predictor.srcs/sources_1/ip/data_mem_256x32/data_mem_256x32.xci
# IP: The module: 'data_mem_256x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/COD/Lab5/cpu_pipeline_IDbeq_forward_predictor/cpu_pipeline_IDbeq_forward_predictor.srcs/sources_1/ip/data_mem_256x32/data_mem_256x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mem_256x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
