# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/expecto/Desktop/Lab/COD_Lab/Lab4/one_circle_CPU/one_circle_CPU.srcs/sources_1/ip/ROM_Instruction/ROM_Instruction.xci
# IP: The module: 'ROM_Instruction' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/expecto/Desktop/Lab/COD_Lab/Lab4/one_circle_CPU/one_circle_CPU.srcs/sources_1/ip/ROM_Instruction/ROM_Instruction_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_Instruction'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/expecto/Desktop/Lab/COD_Lab/Lab4/one_circle_CPU/one_circle_CPU.srcs/sources_1/ip/ROM_Instruction/ROM_Instruction.xci
# IP: The module: 'ROM_Instruction' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/expecto/Desktop/Lab/COD_Lab/Lab4/one_circle_CPU/one_circle_CPU.srcs/sources_1/ip/ROM_Instruction/ROM_Instruction_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_Instruction'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
