# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VivadoProject/COD/Lab3/Single_Cycle_CPU/Single_Cycle_CPU.srcs/sources_1/ip/dist_instruction_memory_256x32/dist_instruction_memory_256x32.xci
# IP: The module: 'dist_instruction_memory_256x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/COD/Lab3/Single_Cycle_CPU/Single_Cycle_CPU.srcs/sources_1/ip/dist_instruction_memory_256x32/dist_instruction_memory_256x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_instruction_memory_256x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/VivadoProject/COD/Lab3/Single_Cycle_CPU/Single_Cycle_CPU.srcs/sources_1/ip/dist_instruction_memory_256x32/dist_instruction_memory_256x32.xci
# IP: The module: 'dist_instruction_memory_256x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/COD/Lab3/Single_Cycle_CPU/Single_Cycle_CPU.srcs/sources_1/ip/dist_instruction_memory_256x32/dist_instruction_memory_256x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_instruction_memory_256x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
